### PR TITLE
Remove encode/decoder in favour of format

### PR DESCRIPTION
**Pull request by akkie**

### CODE REVIEW

**Comment by akkie** [comment]
@datalek Would be nice if you could throw an eye on it :wink:

**Comment by datalek** [comment]
Oki, I'll do it next days 👍

**Comment by akkie** [comment]
@datalek I need the JWT changes for my next work. So I merge the pull request. If you find an issue, please create a pull request or open an issue :wink:

**Comment by datalek** [comment]
Oki, No problem :)

**Pull request merged**
